DROP TABLE IF EXISTS USER CASCADE;

CREATE TABLE USER ("ID" LONG(4) AUTO_INCREMENT, "CREATE_AT" DATE, "FULL_NAME" VARCHAR2(50), "PASSWORD" VARCHAR2(60), "UPDATE_AT" DATE, "USERNAME" VARCHAR2(50) PRIMARY KEY);